booking-system-sept-2017/src/helloworld.java
Change-Id: Iebe1dd6c30a874f5cced02899fcc5eded757d52b
Signed-off-by: zwing <zwing@Ramach-Surface>
=> Initial commit from Zach.

booking-system-sept-2017/src/helloworld.java
Checking if this will show contributions on the contribution page
=> Test commit from test branch

booking-system-sept-2017/src/registration.java
Set up the initial base for the registration class. Created some basic
variables and user input for the information needed to successfully
register. Need to discuss with team on how the information will be
relayed back to be used to create a new customer/user object (still a
bit rusty on java). Validation etc will be done after that is sorted.
=> Initial code set-up for registration

booking-system-sept-2017/src/Login.java, booking-system-sept-2017/src/Users/init_users.java, booking-system-sept-2017/src/driver.java, booking-system-sept-2017/src/registration.java
Change-Id: I9690c91cb71531c567e594e4c8dfdf4b674abe9b
=> Second commit for Login function. Added scanner to driver.

booking-system-sept-2017/src/main/Login.java, booking-system-sept-2017/src/test/LoginTest.java
Change-Id: Ic20a5515025b99cacdf511b3fef5087e1764dc7b
=> Final commit for loginTest.

booking-system-sept-2017/src/main/Login.java
Change-Id: I31bd996154a7bdf9afc1f0ae7fd75a5089680794
=> Added userPosition to login class.

booking-system-sept-2017/src/main/Login.java
Change-Id: Idf683d32c5fc1a981e7068a53878b47e29506310
=> Reworked login function to not use c_ and b_ prefixes.

booking-system-sept-2017/src/main/Registration.java
Change-Id: Iac1caf7725d4cd509c7513923184c2fe29e853a3
=> Added adding employee functions and updated registration validation etc

booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/test/RegistrationTest.java
Change-Id: Icc089fc0ed76d96e19b875df6ad4f70d6ca40a45
=> Employee testing

booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/test/RegistrationTest.java
Change-Id: I6dbb1726ff0c2ce35c5107a5591c0a6030527566
=> Testing and functions updated

booking-system-sept-2017/src/gui/gui.java, booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/test/DatabaseTest.java, booking-system-sept-2017/src/users/Database.java, booking-system-sept-2017/src/users/Employee.java
that availability[times][day]. Also changed the database setup so it
reflects the employee details. Finally added radio buttons to the
employee availability page so the employees times can be changed
=> made changes to the driver function, added a 2D array to the employee so

booking-system-sept-2017/src/gui/gui.java, booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/test/DatabaseTest.java, booking-system-sept-2017/src/users/Database.java, booking-system-sept-2017/src/users/Employee.java
availabilities into a 2D array. Employee availabilities is an array of
type boolean. 
=> Database updated to load and save employees as well as there

booking-system-sept-2017/src/users/Database.java
=> removed debugging prints

booking-system-sept-2017/src/gui/BusSelectEmployeeActionListener.java, booking-system-sept-2017/src/gui/Gui.java
=> Gui update

booking-system-sept-2017/src/main/Registration.java
and adding selecting specific shifts
Change-Id: If02e3764889cdb2bba90935af39b7f3fdb3d67b3
=> Changing registration parameters for GUI

booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/test/RegistrationTest.java
Change-Id: Ia209005bee52f23c1bb8d8365945f64c617f3a65
=> Registration fixes

booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/test/RegistrationTest.java
Change-Id: I2426a91046fd0b141640b2f40f3408a92d04ee64
=> Fixing tests and reg..

booking-system-sept-2017/src/test/MenuTest.java
Change-Id: Ia9af2271dae643f1bb994500f170ab4230df7dad
=> Small MenuTest update to remove redundant code.

booking-system-sept-2017/src/gui/BusSelectEmployeeActionListener.java, booking-system-sept-2017/src/gui/DisplayEmployeeAvailability.java, booking-system-sept-2017/src/gui/SelectEmployeeActionListener.java, booking-system-sept-2017/src/users/Database.java
=> Gui working with buttons changing. now employee available times are

booking-system-sept-2017/src/gui/AvailTimesActionListener.java, booking-system-sept-2017/src/gui/DisplayEmployeeAvailability.java
are booked, available or not available
=> Colour of buttons changed for availability so its clearer to see if they

booking-system-sept-2017/src/test/DatabaseTest.java
=> new test cases for database

booking-system-sept-2017/src/main/Menu.java, booking-system-sept-2017/src/test/MenuTest.java
Change-Id: Id1bf61d64cc7138e3428eaa3555b1db307d6592c
=> Updated menu to have view past bookings.

booking-system-sept-2017/src/gui/Gui.java, booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/main/Menu.java, booking-system-sept-2017/src/users/Database.java
fixes. updated gui and driver to load new booking table 
=> updated database to read bookings table from the database. minor bug

booking-system-sept-2017/src/gui/BookingActionListener.java
=> booking alert. unable to make booking

booking-system-sept-2017/src/gui/BusSelectEmployeeActionListener.java, booking-system-sept-2017/src/gui/Gui.java, booking-system-sept-2017/src/gui/SelectEmployeeActionListener.java, booking-system-sept-2017/src/gui/UserDetails.java, booking-system-sept-2017/src/main/Booking.java, booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/main/Menu.java, booking-system-sept-2017/src/test/DatabaseTest.java, booking-system-sept-2017/src/test/ViewBusiAvailTest.java
=> small fixes

booking-system-sept-2017/src/javafx/BusinessMenu.fxml, booking-system-sept-2017/src/javafx/BusinessMenuController.java, booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
and showed in GUI. Ignore the state/look of the page for now.
Change-Id: Ib4ec3afd09fe19fd530e4b5214e1e105bd456589
=> Adding availiabilities controller

booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java
=> changes to the availability

booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/BusinessMenu.fxml, booking-system-sept-2017/src/javafx/BusinessMenuController.java, booking-system-sept-2017/src/javafx/BusinessViewBookingsController.java
=> Fixed so then tab reloads each time it is selected. keeps data up to

booking-system-sept-2017/src/javafx/BookingSystem.java, booking-system-sept-2017/src/javafx/BookingSystemPreloader.java, booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/BusinessViewBookings.fxml, booking-system-sept-2017/src/javafx/BusinessViewBookingsController.java, booking-system-sept-2017/src/javafx/CustViewBookings.fxml, booking-system-sept-2017/src/javafx/CustViewBookingsController.java, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java, booking-system-sept-2017/src/main/Booking.java, booking-system-sept-2017/src/users/Database.java, booking-system-sept-2017/src/users/Employee.java
times. changed employee availabilities array from [timeslot][day] to
[day][timeslot]. needed for gui and multiple booking function
=> Added preloader. added double bookings and correct sorting of available

booking-system-sept-2017/src/javafx/EmployeeAvailabilities.fxml, booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
Change-Id: Icf8753d4988f63b1beff7d275c002730a926bf45
=> Employee availabilities FXML and functionality updates

booking-system-sept-2017/src/javafx/BookingSystem.java, booking-system-sept-2017/src/javafx/BookingSystemPreloader.java, booking-system-sept-2017/src/javafx/BusinessMenuController.java, booking-system-sept-2017/src/javafx/CustViewBookings.fxml, booking-system-sept-2017/src/javafx/CustomerMenu.fxml, booking-system-sept-2017/src/javafx/CustomerMenuController.java, booking-system-sept-2017/src/javafx/Login.fxml, booking-system-sept-2017/src/javafx/Register.fxml, booking-system-sept-2017/src/javafx/RegisterController.java, booking-system-sept-2017/src/main/Registration.java
registration.java to allow first to fail but last elements to pass.
change to address regex to allow for spaces
=> changes to registration page to show up what is failing. small change to

booking-system-sept-2017/src/javafx/AddEmployeeController.java, booking-system-sept-2017/src/javafx/AddEmployees.fxml, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java, booking-system-sept-2017/src/javafx/Register.fxml, booking-system-sept-2017/src/javafx/businessMenu.css
=> removed some debugging prints and added tooltips to employee

booking-system-sept-2017/src/test/DatabaseTest.java, booking-system-sept-2017/src/test/RegistrationTest.java, booking-system-sept-2017/src/users/Database.java
=> Fixes to a few tests that where failing

booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/main/Menu.java, booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/main/Session.java, booking-system-sept-2017/src/main/ViewBusiAvail.java, booking-system-sept-2017/src/test/MenuTest.java, booking-system-sept-2017/src/test/RegistrationTest.java
Change-Id: I65f59d220cb6eab78e73df3b1d50655703b6a65b
=> Initial code for session logging.

booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
Change-Id: Ic2cf713872a21a3e93a0d21d95e0f88be2738c10
=> Updating board fix

booking-system-sept-2017/src/javafx/Register.fxml, booking-system-sept-2017/src/javafx/RegisterBusiness.fxml, booking-system-sept-2017/src/javafx/RegisterBusinessController.java, booking-system-sept-2017/src/javafx/RegisterController.java, booking-system-sept-2017/src/javafx/RegisterCustomer.fxml, booking-system-sept-2017/src/javafx/RegisterCustomerController.java
registration page. no functionality added yet
=> Added tab panes to registration page and also added a business

booking-system-sept-2017/src/javafx/BusinessMenu.fxml, booking-system-sept-2017/src/javafx/EmployeeAvailabilities.fxml, booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
Change-Id: Ieb63870bdc8f125ec92576949d471acc5a2f7917
=> Availabilities fixes and GUI

booking-system-sept-2017/src/javafx/BusinessMenu.fxml, booking-system-sept-2017/src/javafx/EmployeeAvailabilities.fxml, booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
=> Change-Id: I8ddeb73e9a7f45af0c24e2f9a245276a0d542f9b

booking-system-sept-2017/src/javafx/AdminMenuController.java, booking-system-sept-2017/src/javafx/BookingSystem.java, booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/BusinessViewBookingsController.java, booking-system-sept-2017/src/javafx/CustViewBookingsController.java, booking-system-sept-2017/src/javafx/CustomerMakeBooking.fxml, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java, booking-system-sept-2017/src/main/AvailableTime.java, booking-system-sept-2017/src/main/Booking.java, booking-system-sept-2017/src/main/BookingType.java, booking-system-sept-2017/src/main/Driver.java, booking-system-sept-2017/src/main/Menu.java, booking-system-sept-2017/src/main/Registration.java, booking-system-sept-2017/src/test/MenuTest.java, booking-system-sept-2017/src/users/Business.java, booking-system-sept-2017/src/users/Database.java, booking-system-sept-2017/src/users/Employee.java
Updated with LocalTime instead of array
=> Local time used

booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java
Change-Id: Idca409847ee9f0547197432a79078099e889f2f7
=> Fixed availabilities to work with new system

booking-system-sept-2017/src/javafx/BusinessMenu.fxml
=> Change-Id: Idfae40ffa8485323e529fe73ec13be81239139bf

booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java, booking-system-sept-2017/src/users/Business.java
=> fixes after conflicts during merge

booking-system-sept-2017/src/javafx/BookingTypes.fxml, booking-system-sept-2017/src/javafx/BookingTypesController.java, booking-system-sept-2017/src/javafx/BusinessMenu.fxml, booking-system-sept-2017/src/javafx/BusinessMenuController.java
=> Added Booking types to allow businesses to add new types of bookings

booking-system-sept-2017/.settings/org.eclipse.jdt.core.prefs, booking-system-sept-2017/.settings/org.eclipse.m2e.core.prefs, booking-system-sept-2017/pom.xml
=> Change-Id: Id8072d3e70d07560b63a13ead8a4882fe553dad4

booking-system-sept-2017/src/users/Database.java
=> Change-Id: I66648771deec6aba2f71c2c2ea4bcfb0ebde3a1e

booking-system-sept-2017/src/javafx/BookingSystem.java, booking-system-sept-2017/src/javafx/BookingTypesController.java, booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java, booking-system-sept-2017/src/users/Database.java
=> fixes to database

booking-system-sept-2017/src/javafx/BusinessMenuController.java, booking-system-sept-2017/src/javafx/Login.fxml, booking-system-sept-2017/src/javafx/LoginController.java, booking-system-sept-2017/src/test/DatabaseTest.java, booking-system-sept-2017/src/test/RegistrationTest.java, booking-system-sept-2017/src/users/Business.java
=> changes to customisation

booking-system-sept-2017/src/javafx/CustViewBookingsController.java, booking-system-sept-2017/src/javafx/CustomerDetailsController.java, booking-system-sept-2017/src/javafx/EmployeeAvailabilitiesController.java, booking-system-sept-2017/src/javafx/EmployeeAvailiabilitiesController.java, booking-system-sept-2017/src/javafx/LoginController.java, booking-system-sept-2017/src/main/Login.java, booking-system-sept-2017/src/test/LoginTest.java
=> desktop changes

booking-system-sept-2017/src/javafx/AdminMenuController.java, booking-system-sept-2017/src/javafx/BookingSystem.java, booking-system-sept-2017/src/javafx/BookingSystemPreloader.java, booking-system-sept-2017/src/javafx/BookingTypesController.java, booking-system-sept-2017/src/javafx/BusinessDetailsController.java, booking-system-sept-2017/src/javafx/BusinessHoursController.java, booking-system-sept-2017/src/javafx/BusinessMakeBookingController.java, booking-system-sept-2017/src/javafx/BusinessMenuController.java, booking-system-sept-2017/src/javafx/BusinessViewBookingsController.java, booking-system-sept-2017/src/javafx/CustViewBookingsController.java, booking-system-sept-2017/src/javafx/CustomerDetailsController.java, booking-system-sept-2017/src/javafx/CustomerMakeBookingController.java, booking-system-sept-2017/src/javafx/CustomerMenuController.java, booking-system-sept-2017/src/javafx/EmployeeAvailabilitiesController.java, booking-system-sept-2017/src/javafx/LoginController.java, booking-system-sept-2017/src/javafx/RegisterCustomerController.java, booking-system-sept-2017/src/javafx/SelectABusinessController.java, booking-system-sept-2017/src/test/DatabaseTest.java
=> Javadoc added to GUI classes.
